build: Add 'make local' target
Issue #13.

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -8,3 +8,13 @@ SUBDIRS = \
 	tools \
 	www \
 	$(NULL)
+
+local:
+	@test -d "$(WWW_ROOT)" || { \
+		echo -n "fatal: destination directory " >&2; \
+		echo -n "'$(WWW_ROOT)'" >&2; \
+		echo    " not found!" >&2; \
+		echo >&2; \
+		exit 2; \
+	}
+	rsync -avh --delete "$(WWW_BUILD)/" "$(WWW_ROOT)/"
