tools/dsa: Check input arguments to perc()
If perc() is not given two inputs, print an error.

diff --git a/tools/dsa/dsa b/tools/dsa/dsa
--- a/tools/dsa/dsa
+++ b/tools/dsa/dsa
@@ -19,6 +19,10 @@ column() {
 #    $1 result
 #    $2 total
 perc() {
+	if [[ -z $1 ]] || [[ -z $2 ]]; then
+		echo "error: Internal calculation error" >&2
+		exit 32
+	fi
 	echo "($1 / $2) * 100" | bc -l | xargs printf '%.2f\n'
 }
 
