tools/dsa: Split main() into smaller functions

diff --git a/tools/dsa/dsa b/tools/dsa/dsa
--- a/tools/dsa/dsa
+++ b/tools/dsa/dsa
@@ -27,38 +27,22 @@ output() {
 	echo -e "$@" >> $TMP
 }
 
-main() {
-	# Whether the input dataset contains a header row
-	USING_HEADERS=1
-
-	# Our input dataset
-	FILE="$1"
-
-	# The dimensions of our dataset in rows and columns
-	NO_COLUMNS=`head -n1 $FILE | sed 's/\t/\n/g' | head -n-1 | wc -l`
-	NO_ROWS=`wc -l $FILE | awk '{print $1}'`
-
+# Create a $TMP file for output
+create_tmp_file() {
 	# Temporary file used to store results
 	TMP=/tmp/dsa.$(date +%s)
 
-	if [[ $USING_HEADERS == 1 ]]; then
-		NO_ROWS=$((NO_ROWS-1))
-	fi
-
-	if [[ -z "$1" ]]; then
-		usage
-		exit 1
-	fi
-
-	if [[ ! -f "$1" ]]; then
-		echo "fatal: file '$1' not found!">&2
-	fi
-
-	echo -e "Dataset: '$FILE' ($NO_ROWS records)\n"
-
 	rm -f $TMP
 	touch $TMP
+}
 
+# Clean up $TMP
+destroy_tmp_file() {
+	rm -f $TMP
+}
+
+# Iterate over dataset
+analyse_dataset() {
 	# Output headers
 	output "Row\tPopulated\t% \tUnique\t%  "
 
@@ -78,14 +62,50 @@ main() {
 
 		output "$COLUMN_NAME\t$NO_POPULATED\t$POPULATED_PERC%\t$NO_UNIQUE\t$UNIQUE_PERC%"
 	done
+}
 
+# Print out results
+output_results() {
 	if [[ "$2" == "-t" ]]; then
 		column -t -s $'\t' $TMP
 	else
 		tablify $TMP
 	fi
+}
 
-	# Cleanup temporary file
-	rm -f $TMP
+main() {
+	# Check for file argument
+	if [[ -z "$1" ]]; then
+		usage
+		exit 1
+	fi
+
+	# Check that file exists
+	if [[ ! -f "$1" ]]; then
+		echo "fatal: file '$1' not found!">&2
+	fi
+
+	# Whether the input dataset contains a header row
+	USING_HEADERS=1
+
+	# Our input dataset
+	FILE="$1"
+
+	# The dimensions of our dataset in rows and columns
+	NO_COLUMNS=`head -n1 $FILE | sed 's/\t/\n/g' | head -n-1 | wc -l`
+	NO_ROWS=`wc -l $FILE | awk '{print $1}'`
+
+	if [[ $USING_HEADERS == 1 ]]; then
+		NO_ROWS=$((NO_ROWS-1))
+	fi
+
+	echo -e "Dataset: '$FILE' ($NO_ROWS records)\n"
+
+	create_tmp_file
+
+	analyse_dataset
+	output_results $@
+
+	destroy_tmp_file
 }
 main $@
