tools/dsa: Add a main() function

diff --git a/tools/dsa/dsa b/tools/dsa/dsa
--- a/tools/dsa/dsa
+++ b/tools/dsa/dsa
@@ -26,62 +26,65 @@ output() {
 	echo -e "$@" >> $TMP
 }
 
-# Whether the input dataset contains a header row
-USING_HEADERS=1
+main() {
+	# Whether the input dataset contains a header row
+	USING_HEADERS=1
 
-# Our input dataset
-FILE="$1"
+	# Our input dataset
+	FILE="$1"
 
-# The dimensions of our dataset in rows and columns
-NO_COLUMNS=`head -n1 $FILE | sed 's/\t/\n/g' | head -n-1 | wc -l`
-NO_ROWS=`wc -l $FILE | awk '{print $1}'`
+	# The dimensions of our dataset in rows and columns
+	NO_COLUMNS=`head -n1 $FILE | sed 's/\t/\n/g' | head -n-1 | wc -l`
+	NO_ROWS=`wc -l $FILE | awk '{print $1}'`
 
-# Temporary file used to store results
-TMP=/tmp/dsa.$(date +%s)
-
-if [[ $USING_HEADERS == 1 ]]; then
-	NO_ROWS=$((NO_ROWS-1))
-fi
-
-if [[ -z "$1" ]]; then
-	usage
-	exit 1
-fi
-
-if [[ ! -f "$1" ]]; then
-	echo "fatal: file '$1' not found!">&2
-fi
-
-echo -e "Dataset: '$FILE' ($NO_ROWS records)\n"
-
-rm -f $TMP
-touch $TMP
-
-# Output headers
-output "Row\tPopulated\t% \tUnique\t%  "
-
-for i in $(seq 1 $NO_COLUMNS); do
+	# Temporary file used to store results
+	TMP=/tmp/dsa.$(date +%s)
 
 	if [[ $USING_HEADERS == 1 ]]; then
-		COLUMN_NAME=`head -n1 $FILE | awk -F $'\t' '{print $'$i'}'`
-	else
-		COLUMN_NAME=$i
+		NO_ROWS=$((NO_ROWS-1))
 	fi
 
-	NO_POPULATED=`column $i | sed '/^$/d' | wc -l`
-	POPULATED_PERC=`perc $POPULATED $NO_ROWS`
+	if [[ -z "$1" ]]; then
+		usage
+		exit 1
+	fi
 
-	NO_UNIQUE=`column $i | sort -u | wc -l`
-	UNIQUE_PERC=`perc $UNIQUE $NO_ROWS`
+	if [[ ! -f "$1" ]]; then
+		echo "fatal: file '$1' not found!">&2
+	fi
 
-	output "$COLUMN_NAME\t$NO_POPULATED\t$POPULATED_PERC%\t$NO_UNIQUE\t$UNIQUE_PERC%"
-done
+	echo -e "Dataset: '$FILE' ($NO_ROWS records)\n"
 
-if [[ "$2" == "-t" ]]; then
-	column -t -s $'\t' $TMP
-else
-	tablify $TMP
-fi
+	rm -f $TMP
+	touch $TMP
 
-# Cleanup temporary file
-rm -f $TMP
+	# Output headers
+	output "Row\tPopulated\t% \tUnique\t%  "
+
+	for i in $(seq 1 $NO_COLUMNS); do
+
+		if [[ $USING_HEADERS == 1 ]]; then
+			COLUMN_NAME=`head -n1 $FILE | awk -F $'\t' '{print $'$i'}'`
+		else
+			COLUMN_NAME=$i
+		fi
+
+		NO_POPULATED=`column $i | sed '/^$/d' | wc -l`
+		POPULATED_PERC=`perc $POPULATED $NO_ROWS`
+
+		NO_UNIQUE=`column $i | sort -u | wc -l`
+		UNIQUE_PERC=`perc $UNIQUE $NO_ROWS`
+
+		output "$COLUMN_NAME\t$NO_POPULATED\t$POPULATED_PERC%\t$NO_UNIQUE\t$UNIQUE_PERC%"
+	done
+
+	if [[ "$2" == "-t" ]]; then
+		column -t -s $'\t' $TMP
+	else
+		tablify $TMP
+	fi
+
+	# Cleanup temporary file
+	rm -f $TMP
+}
+main $@
