build: Define 'make local' in www/ directory
This moves the implementation of the 'make local' target from the
toplevel Makefile into the www/ Makefile. Executing 'make local' on the
toplevel calls the target in the www/ directory.

diff --git a/www/Makefile.am b/www/Makefile.am
--- a/www/Makefile.am
+++ b/www/Makefile.am
@@ -31,3 +31,14 @@ $(HTML_DEST)/%.php: %.php
 		$(MKDIR_P) $(HTML_DEST); \
 	}
 	$(JAVA) -jar $(HTML_JAR) --compress-js --compress-css -o $@ $<
+
+# Export build to local webserver
+local:
+	@test -d "$(WWW_ROOT)" || { \
+		echo -n "fatal: destination directory " >&2; \
+		echo -n "'$(WWW_ROOT)'" >&2; \
+		echo    " not found!" >&2; \
+		echo >&2; \
+		exit 2; \
+	}
+	rsync -avh --delete "$(WWW_BUILD)/" "$(WWW_ROOT)/"
